[build]
  command = "npx playwright install --with-deps chromium && yarn build"
  publish = "dist"

[[plugins]]
  package = "./netlify/plugins/playwright-cache"

[[headers]]
  for = "/*"

  [headers.values]
    Permissions-Policy="interest-cohort=()"
