name: CI
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Vale
      uses: vale-cli/vale-action@518a9136acc6e6668ce7c00d367051e0941e87ff # v3.0.0
      with:
        files: content/blog/
        onlyAnnotateModifiedLines: true

      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup Node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: .nvmrc

    - name: Enable Corepack
      run: corepack enable

    - name: Install dependencies
      run: yarn install --immutable

    - name: Install Playwright browser
      run: npx playwright install --with-deps chromium

    - name: Build
      run: yarn build
