name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Vale
      uses: errata-ai/vale-action@reviewdog
      with:
        files: content/blog/
        onlyAnnotateModifiedLines: true

      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
